// SPDX-License-Identifier: GPL-3.0-or-later
//! Reporting & export: turn denials (plus diagnoses) into artifacts that
//! sysadmins and CI/CD can consume directly — Markdown tickets, runnable Bash
//! remediation scripts, and Ansible playbooks. (PDF is deliberately deferred:
//! Markdown satisfies the requirement without pulling in a heavy dependency.)
//!
//! All rendering is pure text building; diagnoses come from the shared
//! [`crate::inference`] engine so reports always match what `selucid explain`
//! shows. This module never requires privileges itself.

use crate::analysis::WhyAnalysis;
use crate::avc::AvcEvent;
use crate::inference::{Diagnosis, FixKind, diagnose_with_oracle};
use serde::{Deserialize, Serialize};

/// Supported report artifact formats.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ReportFormat {
    Markdown,
    Bash,
    Ansible,
}

impl std::fmt::Display for ReportFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ReportFormat::Markdown => write!(f, "markdown"),
            ReportFormat::Bash => write!(f, "bash"),
            ReportFormat::Ansible => write!(f, "ansible"),
        }
    }
}

/// Render a full report. `oracles` holds one optional `audit2why` result per
/// event (pass an empty slice for plain heuristic diagnoses).
pub fn render_report(
    events: &[AvcEvent],
    oracles: &[Option<WhyAnalysis>],
    format: ReportFormat,
) -> String {
    match format {
        ReportFormat::Markdown => render_markdown(events, oracles),
        ReportFormat::Bash => render_bash(events, oracles),
        ReportFormat::Ansible => render_ansible(events, oracles),
    }
}

fn diagnoses(events: &[AvcEvent], oracles: &[Option<WhyAnalysis>]) -> Vec<Diagnosis> {
    events
        .iter()
        .enumerate()
        .map(|(i, e)| {
            let oracle = oracles.get(i).and_then(|o| o.as_ref());
            diagnose_with_oracle(e, expected_for(e).as_deref(), None, oracle)
        })
        .collect()
}

fn expected_for(event: &AvcEvent) -> Option<String> {
    let path = event.path.clone().filter(|p| p.starts_with('/'))?;
    crate::privileged::expected_context(&path)
}

/// Markdown report — one section per denial, ready to paste into a ticket.
pub fn render_markdown(events: &[AvcEvent], oracles: &[Option<WhyAnalysis>]) -> String {
    let mut out = String::from("# Selucid denial report\n\n");
    out.push_str(&format!("{} denial(s) analyzed.\n\n---\n\n", events.len()));
    for (i, (event, diag)) in events.iter().zip(diagnoses(events, oracles)).enumerate() {
        out.push_str(&format!("## {}. {}\n\n", i + 1, event.summary()));
        out.push_str(&format!("**When:** audit({})\n\n", event.audit_id));
        out.push_str(&format!(
            "**Who:** {} (pid {}) in domain {}\n\n",
            event.comm.clone().unwrap_or_else(|| "?".to_string()),
            event.pid.map(|p| p.to_string()).unwrap_or_else(|| "?".to_string()),
            event.source_type().unwrap_or_else(|| "?".to_string()),
        ));
        out.push_str(&format!(
            "**Denied:** {} on {} ({} -> {})\n\n",
            event.perms.join(", "),
            event.path.clone().unwrap_or_else(|| event.tclass.clone()),
            event.tcontext,
            event.source_type().unwrap_or_else(|| "?".to_string()),
        ));
        out.push_str(&format!("**Confidence:** {:?}\n\n", diag.confidence));
        out.push_str(&format!("**Why:** {}\n\n", diag.explanation));
        if diag.fixes.is_empty() {
            out.push_str("_No automated fix available._\n\n");
        } else {
            out.push_str("**Suggested fixes:**\n\n");
            for fix in &diag.fixes {
                let root = if fix.needs_root { " (needs root)" } else { "" };
                out.push_str(&format!("1. `{}` - {}{}\n\n", fix.command, fix.title, root));
                out.push_str(&format!("   {}\n\n", fix.description));
            }
        }
        out.push_str("---\n\n");
    }
    out
}

/// Runnable Bash remediation script. Every command is echoed and confirmed
/// unless the environment variable `RUN_UNCONFIRMED=1` is set.
pub fn render_bash(events: &[AvcEvent], oracles: &[Option<WhyAnalysis>]) -> String {
    let mut out = String::from(
        "#!/usr/bin/env bash\n# Generated by Selucid - review before running.\n\nset -euo pipefail\n\nrun() {\n    local cmd=\"$1\"\n    printf '  $ %s\\n' \"$cmd\"\n    if [[ -n \"${RUN_UNCONFIRMED:-}\" ]]; then eval \"$cmd\"; else\n        read -r -p \"Run? [y/N] \" _ans\n        [[ \"${_ans,,}\" == y* ]] && eval \"$cmd\"\n    fi\n}\n\n",
    );
    let mut ticket = 0;
    for (event, diag) in events.iter().zip(diagnoses(events, oracles)) {
        ticket += 1;
        out.push_str(&format!("echo \"== {}. {} ==\"\n", ticket, event.summary()));
        for fix in &diag.fixes {
            let review = needs_review(&fix.kind);
            out.push_str(&format!(
                "# {}{}\n",
                fix.title,
                if review { " (REVIEW REQUIRED)" } else { "" },
            ));
            if review {
                out.push_str(&format!("echo \"    $ {}\"\n", fix.command.replace('\"', "'")));
            } else {
                let quoted = fix.command.replace('\'', "'\\''");
                out.push_str(&format!("run '{}'\n", quoted));
            }
        }
        out.push('\n');
    }
    out.push_str("echo Done.\n");
    out
}

/// Which fix kinds embed shell syntax and therefore must only be echoed for
/// human review instead of offered to the `run` wrapper.
fn needs_review(kind: &FixKind) -> bool {
    match kind {
        FixKind::Restorecon | FixKind::SetBoolean => false,
        FixKind::SemanageFcontext | FixKind::PolicyModule | FixKind::ContainerVolume => true,
    }
}

/// Ansible playbook - one task per fix. Simple argv commands use
/// `ansible.builtin.command`; compound pipelines (`&&`, `|`, `;`, backticks)
/// use `ansible.builtin.shell` and always carry `changed_when: false`.
pub fn render_ansible(events: &[AvcEvent], oracles: &[Option<WhyAnalysis>]) -> String {
    let mut out = String::from(
        "---\n- name: Selucid remediation\n  hosts: \"{{ target | default('all') }}\"\n  become: true\n  gather_facts: false\n  tasks:\n",
    );
    let mut ticket = 0;
    for (event, diag) in events.iter().zip(diagnoses(events, oracles)) {
        ticket += 1;
        out.push_str(&format!("    # {}. {}\n", ticket, event.summary()));
        for fix in &diag.fixes {
            let name = format!("{} / {}", ticket, fix.title);
            let yaml_command = yaml_escape(&fix.command);
            if needs_shell(&fix.command) {
                out.push_str(&format!(
                    "    - name: \"{}\"\n      ansible.builtin.shell: \"{}\"\n      changed_when: false\n",
                    yaml_escape(&name),
                    yaml_command,
                ));
            } else {
                out.push_str(&format!(
                    "    - name: \"{}\"\n      ansible.builtin.command: \"{}\"\n      changed_when: false\n",
                    yaml_escape(&name),
                    yaml_command,
                ));
            }
        }
    }
    out
}

/// True when a fix.command embeds shell syntax that `command` cannot run.
fn needs_shell(command: &str) -> bool {
    command.contains("&&")
        || command.contains("|")
        || command.contains(";")
        || command.contains('`')
        || command.contains("$(")
}

/// Quote a string for YAML double-quoted style.
fn yaml_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::avc::AvcEvent;

    fn httpd_event() -> AvcEvent {
        AvcEvent {
            audit_id: "1788956400.123:456".into(),
            timestamp: 1788956400.123,
            serial: 456,
            result: "denied".into(),
            perms: vec!["open".into()],
            scontext: "system_u:system_r:httpd_t:s0".into(),
            tcontext: "unconfined_u:object_r:user_home_t:s0".into(),
            tclass: "file".into(),
            pid: Some(1234),
            comm: Some("httpd".into()),
            exe: Some("/usr/sbin/httpd".into()),
            path: Some("/var/www/html/index.html".into()),
            dest_port: None,
            dev: Some("dm-0".into()),
            ino: Some("123456".into()),
            raw: String::new(),
        }
    }

    #[test]
    fn markdown_covers_event_and_fixes() {
        let events = vec![httpd_event()];
        let oracles = Vec::new();
        let md = render_report(&events, &oracles, ReportFormat::Markdown);
        assert!(md.contains("# Selucid denial report"));
        assert!(md.contains("httpd denied open on /var/www/html/index.html"));
        assert!(md.contains("restorecon -v /var/www/html/index.html"));
        assert!(md.contains("Make the label permanent"));
    }

    #[test]
    fn bash_script_has_confirm_wrapper() {
        let events = vec![httpd_event()];
        let oracles = Vec::new();
        let sh = render_report(&events, &oracles, ReportFormat::Bash);
        assert!(sh.starts_with("#!/usr/bin/env bash"));
        assert!(sh.contains("read -r -p \"Run? [y/N] \""));
        assert!(sh.contains("RUN_UNCONFIRMED"));
        assert!(sh.contains("restorecon -v /var/www/html/index.html"));
    }

    #[test]
    fn ansible_uses_shell_for_compound_commands() {
        let events = vec![httpd_event()];
        let oracles = Vec::new();
        let yml = render_report(&events, &oracles, ReportFormat::Ansible);
        assert!(yml.starts_with("---\n- name: Selucid remediation"));
        assert!(yml.contains("ansible.builtin.shell"));
        assert!(yml.contains("ansible.builtin.command"));
        assert!(yml.contains("changed_when: false"));
        assert!(yml.contains("restorecon -v /var/www/html/index.html"));
    }

    #[test]
    fn yaml_escaping_handles_quotes_and_backslashes() {
        assert_eq!(yaml_escape("a\"b"), "a\\\"b");
        assert_eq!(yaml_escape("a\\b"), "a\\\\b");
    }
}
